### ISSUE TITLE
Problems creating an admin account

### ISSUE THREAD

**Issue by Joeyarrabi** [lordkator/ZonamaDev#171] opened 2016-06-30 11:37 UTC
I have set my admin_level in the database to 15 and have restarted both the server and my client multiple times.  I have put my client in debug mode and I am using the SWGEmu Launcher.  I have looked around for a solution elsewhere but was unable to find one.  After setting my admin_level to 15 and restarting my client (In debug mode), I do not get the "God Mode" text on my screen, or the SWG Admin tag by my name.  There are no problems connecting to the server, as I can get in the game just fine.

![db](https://cloud.githubusercontent.com/assets/20224491/16486866/09247892-3e8d-11e6-8e3b-6c4e37ff8d46.PNG)

![cfg](https://cloud.githubusercontent.com/assets/20224491/16486904/2cba5196-3e8d-11e6-9dc9-7ab520ed8297.PNG)

**Comment by karlbunch** [comment] 2016-07-01 23:57
Duplicate of #170

**Closed by karlbunch** 2016-07-01 23:57 UTC
